apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: registry
spec:
  host: micro-registry.oichman.net
  port:
    targetPort: 5000
  tls:
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIFhTCCA22gAwIBAgIJAO0FKTdnyAWVMA0GCSqGSIb3DQEBCwUAMFkxCzAJBgNV
      BAYTAklMMRAwDgYDVQQKDAdPaWNobWFuMR8wHQYJKoZIhvcNAQkBFhBvcmVuQG9p
      Y2htYW4ubmV0MRcwFQYDVQQDDA5jYS5vaWNobWFuLm5ldDAeFw0yMzAxMDgwNzQ3
      NTRaFw0zMzAxMDUwNzQ3NTRaMFkxCzAJBgNVBAYTAklMMRAwDgYDVQQKDAdPaWNo
      bWFuMR8wHQYJKoZIhvcNAQkBFhBvcmVuQG9pY2htYW4ubmV0MRcwFQYDVQQDDA5j
      YS5vaWNobWFuLm5ldDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAN/Q
      UfUj8EQjCApLsb2GXi34XrZOUNUpqj6QFW1ynM4p4scPVffdxVbOKXdxsBR0X9QT
      1VLUP+20PHB429iJ+nxXM6Wk9PvAvtdV28KU2wbBKpWVYo6WfdclghIVxJHtB4iX
      rKH3nKHS1ZwnKjO0JsxTvlTEN8Ouc8YyjdkYpxMTLsxcemDfmMaM2iwu8llEAJYP
      p6B+lhcMTSVzAu7KJ3jDH+eBLhtuwyMBVOf7yAKoeR9n41G7nxI7t5rQQYDvzxXh
      5lTzVwQzpimic/Pj0s9CK0oEAVRh5OddCK1OfIWcgSpIMDXpTfYd+jDkKitn2GPg
      SMIbNE1JyWxlAypuAt8YLA/EXNhj+qlA4jX+N8RjSHItYSTR/VChY6gCN8idB2AU
      v9GRR/nohVJ8FdTZE/eAHRrMJXXIcA+oYVPbGQR0G66OikRZDQGBg+eIAATAAhJt
      i4svx/14WtSKq5Fz1llazLDVlUk6izPONVE7iBRkFWg0aQVaewwg+VUAteASOCXK
      KI+O4hOU4JScgRH4/mK6Adb8kx6B9kKcsVIgjfwq0WOa5IqxMfpzTee/i+ZMYHz0
      zsj9A4dZqsGssD+2LFJ+IP2L+9cSamXt7T23YLTuCOkARnTO9csLxMjADZ3Y7foJ
      xBD1qaT8tods/p66fSBJzVVGpCmEhTzv6OoW6QORAgMBAAGjUDBOMAwGA1UdEwQF
      MAMBAf8wHQYDVR0OBBYEFNQbgN3ZRElZ3022ATiZEVhPSBLaMB8GA1UdIwQYMBaA
      FNQbgN3ZRElZ3022ATiZEVhPSBLaMA0GCSqGSIb3DQEBCwUAA4ICAQBX4LQDwl4n
      goEi7DoyPt5eHoZk91/dUfp2uNNg2IZ8Zoyji03Potu+haMTEjq2etwzVl2XdRPf
      YQx95UTqvW2ICry4J026GAJrwCDXUm5T3XOoDL5crfe8OyiDk7EMe9aIHDnpTe3q
      fch2SkdFhvZLH4/8iMCjHvxR3FJ2OdT/bE448nAR50Q00i5I5BA/FogijWmcnGo3
      EdpS8GawhXBLqRBUr/8KSAwS02OXI5vLVO3/pVcQX6cXC0t+qAB46mLWTx/J6vYA
      M86Xxbv/MEhOaYeb9mmvQBpcmebm8fax3z/mo/esvI0kkvki/K9EZz/zebSYrTKh
      jQJeejfFA5iMo90vPTeeu/goFjjlfWm0FmzpylAiy8J9Dp9fts97Hjb1kmUIUnQg
      5Ex3y07+0XrFDBKlA2z/saXeSgGreq50quR6Nt4+GFceucDtJbgs6iSa7dtZzDWD
      PFZpaud//J/1rus4OnFHpopfsBQdwJkRvjl+gVFWLepjWSsM/EfCyj7Dps2xYAx5
      3Rl7MGUS3HR4iNLA/C4ZUlCZS/yQemHcr7e19GvDUgL5cLIsaI3fbxrppiQe+BUr
      SfDjNwuBoWFqK8wY0Nm88Fg7vf92C2cTdMWmHswkm7bPys+d8zJjElUtTkKm/p5m
      auQX+oS/OMMHcEMUZ9C60yYN1ledImUZlQ==
      -----END CERTIFICATE-----
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIF7zCCA9egAwIBAgIUeumG7Tezsh9/bNRpWQ+28u8Cou0wDQYJKoZIhvcNAQEL
      BQAwWTELMAkGA1UEBhMCSUwxEDAOBgNVBAoMB09pY2htYW4xHzAdBgkqhkiG9w0B
      CQEWEG9yZW5Ab2ljaG1hbi5uZXQxFzAVBgNVBAMMDmNhLm9pY2htYW4ubmV0MB4X
      DTI1MDMxMjE0MDAyMFoXDTI3MDMxMjE0MDAyMFowgY4xCzAJBgNVBAYTAlVTMREw
      DwYDVQQIDAhOZXcgWW9yazERMA8GA1UEBwwITmV3IFlvcmsxDjAMBgNVBAoMBU15
      T3JnMRIwEAYDVQQLDAlNeU9yZ1VuaXQxHDAaBgkqhkiG9w0BCQEWDW1lQHdvcmtp
      bmcubWUxFzAVBgNVBAMMDm1pY3JvLXJlZ2lzdHJ5MIICIjANBgkqhkiG9w0BAQEF
      AAOCAg8AMIICCgKCAgEA3ZXDWmBXDpRHN5v+WWUGU1HaGUooz3HO6wT5CsX5TL8a
      YWPA/16Q4r40viFZxtVr4maP3xaOT0354xPFd1hV1793YhqBXLupZT61RU53EP1o
      dHpSBCUG2abDlu3Q7uC8JG2UCBK13QhCAsE2vLH5gJC/znERCyokFSN9hnkBSpHG
      furN+NTLoDoaYBOIGVKbfVxJkLGn8KtzOmBYyKZR6Qbd5eI2Nj6aIbk2NiffVQmZ
      V20UaI0HVOLZXogb/CqunhcVTXuLLhl/yoZcXLinZYetk/fOOr3XM5ohvK8LjsS7
      QIkec+Z9vmO3gzwOf3Gki4kPjPfxXNRZCOoMWHEEk+/FqSSdWLZjU1mhdKy3RSrP
      C6LtClZzbb23dxmnyYjoTVZncsvqVpnQhu6Rm6T6MzqEPFAVBGwo/d4TpSu2B6J9
      xuvuA33acU81VUGGuWAONYhh+gvbtMNL9YS987ppD5oykPm131ftkqsDdgDeqOcV
      LX1xVUFXHSYnhN7/uoI7GidzOIKBzuy6vxgTWgD2ExNEiHDDRC9Z7Fe+/8ceSDA5
      +iC6GmDWh0j6zi7skWWud7QEmtCeYCLmbmu7aa3Xw9YQgjKhpoo6JZSm4yFFSedK
      apmDjpkUaLqdh5MzTHa4pak1LLrg/rR34dihdv/Bx4N1Dl9nKPqTwtplTzwstFEC
      AwEAAaN5MHcwNQYDVR0RBC4wLIIObWljcm8tcmVnaXN0cnmCGm1pY3JvLXJlZ2lz
      dHJ5Lm9pY2htYW4ubmV0MB0GA1UdDgQWBBTWNuhoCSNbyjrM26xQVMzIIloYYzAf
      BgNVHSMEGDAWgBTUG4Dd2URJWd9NtgE4mRFYT0gS2jANBgkqhkiG9w0BAQsFAAOC
      AgEAHN9SLGo5eWbW05HcZbL/LTNymitwbtKwZXKJzrMMJ324n+apvhhI4TZKrnfM
      AzfXnIv7c4KBgy4SQhzbgR8fUrRxbQqUoK1w7K/KWNrrBcgmI49TcnKEBfuZikYm
      BnNZs17lq9AT2T6HqfRN6dLu5bk4gcxJ2k7Ib3+NwIWSw89hKblW3G/YPj7PKvtJ
      FRF6TxZYpiZL8Ult61okN4o9Z/L4bTRaRtAcWTpfIBvW9NyAIVGj9llEbl+h7ejH
      37bCp/1lrEFafvcCpP/+n2bkfl8p9YXXRrjIxSY1zDc6rtHE/D7LIx/8rJzpiug4
      C+eJQkE93Mp1Ogi6+d7Q9ZQuLjclakcx2mjE2a3FJftIPgQHMlnHUYpj5y6iSLMf
      qD0lERTNuZn1gU7sXIktvK8Rv75DTbRMsNH0cgsGFLYmGazsqlBJaw2HhlkNVUHO
      7S97sqMZXllLimKG5tZOAKe2AS9nJ49jjOTRYGbKVATBDLmBug4Y66dcTuCMAzg9
      Ng1WKLnMYp2sgWaH2np+7eQ3r4ZMjPs00KpGNhUUfxgGolZ+89eJ/r1HVqDgR+Af
      g/mHcCfNb0mnffI2Kbbuv/5Y7K+CoVbEeBf4yNW6CIGrtEU5+DbxJtI7gNlWyIgw
      OpWHS7b8cgEFCR5ZcexU9KICEfS+q6+98DY4tUQbNcuEMNw=
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Redirect
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKAIBAAKCAgEA3ZXDWmBXDpRHN5v+WWUGU1HaGUooz3HO6wT5CsX5TL8aYWPA
      /16Q4r40viFZxtVr4maP3xaOT0354xPFd1hV1793YhqBXLupZT61RU53EP1odHpS
      BCUG2abDlu3Q7uC8JG2UCBK13QhCAsE2vLH5gJC/znERCyokFSN9hnkBSpHGfurN
      +NTLoDoaYBOIGVKbfVxJkLGn8KtzOmBYyKZR6Qbd5eI2Nj6aIbk2NiffVQmZV20U
      aI0HVOLZXogb/CqunhcVTXuLLhl/yoZcXLinZYetk/fOOr3XM5ohvK8LjsS7QIke
      c+Z9vmO3gzwOf3Gki4kPjPfxXNRZCOoMWHEEk+/FqSSdWLZjU1mhdKy3RSrPC6Lt
      ClZzbb23dxmnyYjoTVZncsvqVpnQhu6Rm6T6MzqEPFAVBGwo/d4TpSu2B6J9xuvu
      A33acU81VUGGuWAONYhh+gvbtMNL9YS987ppD5oykPm131ftkqsDdgDeqOcVLX1x
      VUFXHSYnhN7/uoI7GidzOIKBzuy6vxgTWgD2ExNEiHDDRC9Z7Fe+/8ceSDA5+iC6
      GmDWh0j6zi7skWWud7QEmtCeYCLmbmu7aa3Xw9YQgjKhpoo6JZSm4yFFSedKapmD
      jpkUaLqdh5MzTHa4pak1LLrg/rR34dihdv/Bx4N1Dl9nKPqTwtplTzwstFECAwEA
      AQKCAgAF81+rraqo2ZKQC8Bo5i2lTy1sQHGYIJZN+XQ2tdpcFUXAF823DfMWI8WG
      1Z5zmIetLNPwScrIlm9/iahj7BtiD+JE4DFZLDEAZw63LcRE0Ildl2tccSId9jyK
      cRiLUb27vLWdAeOga/hZ2pZ9usnYigqcoKy0gA04BBv64IUIW6HZBrVBWXWed/D9
      Y4jkJTPHyhKvsBWygOg3SR8ZRF4uw+BxrAGIs2WwQikSiz+UKQ3VKzjBFgh8Xxs3
      TrBxtTO7SyNnUUoLkuO7rKAOXWchcuNWdfEz4qVE3X7Kcmj9DIt60DPhKO93jXYA
      MDyzb3nbxXKFdqMkuw8pDiAGwAI/agYW0+9mOsg4YRUhs4aSSA1IWwhGfbEAr7gE
      /s4F6IwxrVxIE5zugNT7okohK68CBrV+yvKEkvZ3m3mrS7johLZ1W4uhio4lK8YD
      4Fk5rkFBIvIc3CroMTL1RwJ5qHgUubiZPSPPJt6pTwD21IMmpETBynniLkBCY2d9
      1VOGk7ujQPNX3Gxs40R+dEmDZqFRdyFnqYi3jdvgq8G/MGH7zpzmJeyz/ZQ35I0s
      C8T+9xDl6rLUdrxojFouuVkZV4qwlmDgRGvFistDFwyI1z9WFliS3o3MXOA42cdR
      ufkIG1XNdR/NWLIztoy9/WQYoAbsGHI3HGeSYob2c33zJcQvgQKCAQEA77jfyE3C
      g35BjHuz/4jYWIjtfEAv2RXM4PG+sBolzUf8yuyjfQ0njA5ja4uBaTYC5DGelUuw
      l9AGUGN5CNXkFJBfjj5duTQYPExAztzsaiS7eI//y87Iwnn22+geUoAoWjpeHQ2F
      cI9CxqfLSk8AunmIjxMG8oNLqmaIdsGVa95ew+ZtRyq8ogGWe1AyMRBFnCBbNp0K
      em1ETw7fpTrGAzPTWRWN2pHzrZFcfEB0HLXlzI1qZXBBNOIZCILhuiOyUg1BwU21
      9x+gP4nlwNOmh0CLsD4a/he6fb/0RwlNQBKC0e+3Zm1FzmLjX0t0c/zo15r9tV0e
      TWOwq7YIeKt1VwKCAQEA7KGbry/aiTq4AwlroqtAza7JKOkkGDP5MZ14lVUZd9Ra
      ypztk/QmEefjnhzfNMIx1TqLDAzjUr3UXKE5UM87LFSqkL4I8Ong8LOagQxqIIol
      q0ZekrPZ84/jnBI+3lkFPggPHkApzhYkA3IXTGHQ/GeQGONyXG+nD0MiGz69oa0r
      mB4hX/P4vI8EbQ7WVjFs0XzJ4/wtHScNUs8dfs8eBDGtWdiiTTgk8xyOpuJoVKCS
      i24Ae1gdp80x9wdEXivneCnZRa+U2yHPeBOyWpmW6YrbjBVReJMe0clIowkc1TUl
      5/X4v5J/xW8Y7WVtADLQzK3pTSPRWl+jR6UAZ6yylwKCAQEAhWhlYZukvHjvEbdm
      HLeTbvIE+DjgZ/dx5V2juW1TzEJbtLKs6VMAxzjaq2cfxeWBBm12y68rv9DNMr+p
      A/nEzIzsIMUkc4VCV4w4JOddylRW4GmC+XFC2Lf3Ybpz5YXc7xm8dn6n3FRd3SBU
      Si5dQWmRTc5Q93WKDnKxTyW8eiNuqab6+bgW8jHgBRBEXnmnw5NeL66FvkxAz55/
      Z/ylZfLZk6IjJ5hB/D4BMkTMWY4BLS0mIP2vzDZnqAzugiCLhI5MIb+VnMnE7JdZ
      fU5MRsjs9FAbxXx/FKxWzZGnpBipJRw6/I2jY5A06Tucu0/sZNCkkOIZkwf/sg/D
      9yO0UQKCAQAITfOkxk0pG8JxeNcqMlBn54ZvxR7bKpfIQfqFYyMtrWoySiecVakw
      X68BUYoT0+zjytYuahVgRgE57v6P83XkLGSAB+tQaSTXzbXSaZkf4zlHNYUEKQOx
      JI+cXpeOPhmM/8NoEGBnNye0Z0CiEZy//vJzrSfKTrDSPEzqH92P2v/4qrYJJArK
      s0o4eZjUFY/4GiULt0HuD/zLtzEVzjcDdqrayFuJ0jqZvZrUCIYY0jnSYt3pdkI0
      LWNfhAXGOEw7T1yssWjL9/fMAwTzYQiG0bS6ydS+IoumWSYPcrZsVR0rctpz/rQ1
      PZzmV/TnWOEzDbduWZ9zSH/2d7f363upAoIBACPuFrDE8gONHbtPK8q/QAhYRYnl
      FomG+/AqIxyNyckEIGQZKvUrWzDfdsR4EraPRp0wgoBUJwXFcGZAJ4LcqV8Ol2lg
      wUQbLcJBX/deaiI8kWVWyBOPXqNphCDaqQ7fE/UKcx85x3718x3zjuoLLMvwMEXZ
      0IEDQjlfWXCQDnqKChmlA1+R+T2dIyhJxnYkvDw5g6b3pNXIqV6TmOYZqDSZNekL
      HJ494oLNW3kgieNlWCmg86ONFtXI8yaN9mrFcCAMZChE2Gk9DVnQ8f1+eGnLWzCk
      /TC1m0s1QOfAKkj/FqYXL3Uw1A6lmZjIrGQFAGYHIhsQLP2H0oVNfN4SPGY=
      -----END RSA PRIVATE KEY-----
    termination: edge
  to:
    kind: ""
    name: image-registry
    weight: null
status: {}
