apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: registry
spec:
  host: micro-registry.oichman.net
  port:
    targetPort: 5000
  tls:
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIF/DCCA+SgAwIBAgIUFZy2Ieu28UoPfL4y1i5XY1GZB7EwDQYJKoZIhvcNAQEL
      BQAwgY4xCzAJBgNVBAYTAklMMRAwDgYDVQQIDAdSYWFuYW5hMRAwDgYDVQQHDAdS
      YWFuYW5hMQ8wDQYDVQQKDAZSZWRIYXQxCzAJBgNVBAsMAlBTMSIwIAYJKoZIhvcN
      AQkBFhNvb2ljaG1hbkByZWRoYXQuY29tMRkwFwYDVQQDDBBjYS5pbC5yZWRoYXQu
      Y29tMB4XDTIxMDEwNzA5MTUwM1oXDTIzMDEwNzA5MTUwM1owgY4xCzAJBgNVBAYT
      AklMMRAwDgYDVQQIDAdSYWFuYW5hMRAwDgYDVQQHDAdSYWFuYW5hMQ8wDQYDVQQK
      DAZSZWRIYXQxCzAJBgNVBAsMAlBTMSIwIAYJKoZIhvcNAQkBFhNvb2ljaG1hbkBy
      ZWRoYXQuY29tMRkwFwYDVQQDDBBjYS5pbC5yZWRoYXQuY29tMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEAyy0Uqwi3xmPBC1HkKHHWdoLjxSq+keOSRzBX
      MEWtw7VqCOuOheBxMtN2OMjbnd1f53fkZVSC0I2MzuXFE1xS0LSurtz60ogVII58
      MvgEsJvWCVT6eSpMSgVg/GFSHzgDTS+jSu/c8DzRuL1oYIDJ9NBzy+8HjLWOrF+H
      bFVUpFT5rkA5Fo7SbcypUwFTAyXHKg8Li4w0FggMSWHLTBqvXYvlstF/t9QOkivs
      a0+eW2pZYtgSEtz+uGkUgyAF9uvQrenw/M/vrkiM/H3ZFIHPQfu25nhIrUvYYlSC
      XEyRZsqo9fsntkyT+7r+oSz09B5MF2VotCuM8FKZPboRL16KLZ8UeRg1HvZtVgqS
      4fTt89GNrI+rVUgvLfWv2eAekHmUrKgvSpF8EtNdz9LvmZ/eNBMInUAdduL0FMJw
      tmXgzqN6P6HOCo6ehgr8bvWKR9Rvyd/Czow4Dk8gth3Mk8RiiZWIhr4jD0VG/Puc
      0RDlpIRUzQyrsE9E1yvJEqq+1pDSaQcMaTI/aQDZvxVzm+9xMbPYRNFNxuBkc/bx
      GmRt8/RsKrJRG5LyMa63tlnVn9CKfjWPuG86bjRS2bFvr0m8VU4OAnDt18TVuldA
      /Ua+MOOzWmZtn5uhzSgmiPKTQiNe1i7deC24OCUZFz3/lVuDCxkfOSymYaeeJIIx
      OJLf+dMCAwEAAaNQME4wDAYDVR0TBAUwAwEB/zAdBgNVHQ4EFgQUBZ6MSTSaZ1zT
      Poj1N5atqDYA8Y4wHwYDVR0jBBgwFoAUBZ6MSTSaZ1zTPoj1N5atqDYA8Y4wDQYJ
      KoZIhvcNAQELBQADggIBALjrJV9MStlMx4ikkJFst5F75L3US5KZRz5Knjjfn7Yw
      RtCV032NzK6ocpRK1WOynzLf2JvdT3X4VKnc5weqt+VYZ9dUpU4CNl5ASHKbaigw
      qjthW25K8rBvh7GlRM7VURsh1bz/KKvkLEpGr2C6Z9Hvknb0Rd0lObASkV1ucpFx
      uweCa7VX3b0U8CBXIo9ZYSzpy6PW6BMHTbJq9oTLTVZuxZCCW9gxPYy4iAMYkAej
      hsQzH7uAhAX8EfvKmXIrmdAxujE5IYP7B3gSueENWwb0moRiDriNQoPBfdmep2ob
      IroQ+YKj7JFhPMYrx3vh7fKiObt+qdjKyXO54eEz8uwUrZmOwHzNcg2xqaWWJYZh
      r24haOeCitiDmrxeQYV/T+huwEfWzFU0a8nNgqy1O1Vl7d5egqEUQGbs0ZQoc6cw
      VNVZ64jkUYH7ZlJUH9zLHcafUOKX7L2DWFl/012HcezSckZsq919ZTThHpLUo0TW
      jPbpoWDXczYqQNF/EeXMPTcL16Cvrp84Yec4m3gTmot9ZzA51kiq3ATm/uPyG6Se
      wBa16LgMLIjHfaXi2+X/SqzOAkpOAgg39uba5+F338n+ssinojVM6lMlLnkVtRnP
      Io9tCCfumDBvpto3uohtYvcDk+Y4z4DLOQyyK06B94TB9zzsD7xfzuFesnph+FZE
      -----END CERTIFICATE-----
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIFrzCCA5egAwIBAgIUeumG7Tezsh9/bNRpWQ+28u8CougwDQYJKoZIhvcNAQEL
      BQAwWTELMAkGA1UEBhMCSUwxEDAOBgNVBAoMB09pY2htYW4xHzAdBgkqhkiG9w0B
      CQEWEG9yZW5Ab2ljaG1hbi5uZXQxFzAVBgNVBAMMDmNhLm9pY2htYW4ubmV0MB4X
      DTIzMTAyNTEyNDIyM1oXDTI1MTAyNDEyNDIyM1owgY4xCzAJBgNVBAYTAlVTMREw
      DwYDVQQIDAhOZXcgWW9yazERMA8GA1UEBwwITmV3IFlvcmsxDjAMBgNVBAoMBU15
      T3JnMRIwEAYDVQQLDAlNeU9yZ1VuaXQxHDAaBgkqhkiG9w0BCQEWDW1lQHdvcmtp
      bmcubWUxFzAVBgNVBAMMDm1pY3JvLXJlZ2lzdHJ5MIICIjANBgkqhkiG9w0BAQEF
      AAOCAg8AMIICCgKCAgEAv30iSLUcv4RxoYZFaLnbeVsCZovr7PKatxAgUY7I/y/h
      x3m4BBAyYyVlGwvgZ1PFco3zWaxlmEkf5qvHUGeFfmpGg9Hq33z1WGBF/UmU1IVg
      Uq1PN/TSF6fbX9KTbAvju8min12LQI7JIZIDPADEMkQNc56NAsX6i6Ff6x7cnvrt
      MV7Bpowu4WZdiGvnDvoKrQpoS0dfkZ6zV7snPZtGEDF+HjtOrm7bawChq5JSSV71
      mw5RcgIDCTa04MGDJXpIw3ZHANfI2odvxi3LXHQwtdzu+K9UFJiK9N6VzbjPssVM
      vnqF8vaVt4+GXMBkVorc6bDC/richwWdODOtPxhkVhdLGdKETbpQaXQ0Syrcbod2
      JEWC5IdmpeS9i1Zh+KNK8QcJPc7rKEdsnz7X1d6N9wy+7vAS1q/HWiVO2FlPv0kF
      Fopz7uw6GBstli7RShaO3wBFIM6/8rMKy1RqXD/TKoDRVDfy7m9hBNdU5HDjlLBb
      02MgpdV3PzwSt11gMxmEM+hIVfokQ7+bVjDh0iL63UiMHeOaRCZXX3xNhXd7MlUe
      ksJliz84O7j5KEGR3XfFmRkrqQ4lN0F1hkXshyHCW2ah8DShH01KGtEgVPn3b2cb
      /j8uLVImRK8uXtVmmYKuPniRfwUC47Yvp5rPfG+WukUqzoj30Nm1GQFX5rA/E3EC
      AwEAAaM5MDcwNQYDVR0RBC4wLIIObWljcm8tcmVnaXN0cnmCGm1pY3JvLXJlZ2lz
      dHJ5Lm9pY2htYW4ubmV0MA0GCSqGSIb3DQEBCwUAA4ICAQAQrhBjgsmJWlXDFHcj
      V7OQNhFgpeH+DoO3NcmnmL8Mtp+Ru9NevDuazhCLYlEWnyqfQ1Fkkg73yXDFLYiK
      CVz2EUzEpsvlehr5CQNeqBLq5ttgqd99o5JUMvC/L0z4FMSP+zfK4oqvrh4AbU8A
      O5pZbfm3G2pTHEOcatX+d01LAN1b4q+3OgxvXazzBSD4d+vQ9mLj466oYyq0pYeF
      h5NCPa7dVL1/a/1e4SO7YOzGSb2rvhY9joWOMpNnbDomJXl4eYKbb1lf1bfJVCtX
      0rARpRU6QxgjyKMQcD7rK5Kx/3dayGYMIu30e0ladnsi5NJ3vh4nzvvd0yCVDRtY
      X1icGdsJGwozGEaJxubTNLJ/2LeBPJYMFhw3Al28ZdUYfy7TpowsEiC/kz2zjdAl
      KFjjDVnWoUa4SwRHcfZ7JlCRKewqOyFaQwpjljTiRkfXdv1VLIkYzX6mTEcsw95j
      8AV8WLL0bdUGjbQT3PARinD44bhOqJdaAGhMIMDSuViQE1BuFBWOAdQRVS3lOPZ5
      qrSnWaBozZARH5UCRfhqiGJWG0bZ6b5e8fZ2+BpbaftKREJu+mFY/MtYoeozFQhG
      DTaaNG2rYOExeUsHytmKzQaLA0ZluSOkteLu+Xrp1+AKtkg/6Ym6xe0jUBHx9gkV
      rupH6mx52b5kmX0z+sN2I5aXyw==
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Redirect
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKQIBAAKCAgEAv30iSLUcv4RxoYZFaLnbeVsCZovr7PKatxAgUY7I/y/hx3m4
      BBAyYyVlGwvgZ1PFco3zWaxlmEkf5qvHUGeFfmpGg9Hq33z1WGBF/UmU1IVgUq1P
      N/TSF6fbX9KTbAvju8min12LQI7JIZIDPADEMkQNc56NAsX6i6Ff6x7cnvrtMV7B
      powu4WZdiGvnDvoKrQpoS0dfkZ6zV7snPZtGEDF+HjtOrm7bawChq5JSSV71mw5R
      cgIDCTa04MGDJXpIw3ZHANfI2odvxi3LXHQwtdzu+K9UFJiK9N6VzbjPssVMvnqF
      8vaVt4+GXMBkVorc6bDC/richwWdODOtPxhkVhdLGdKETbpQaXQ0Syrcbod2JEWC
      5IdmpeS9i1Zh+KNK8QcJPc7rKEdsnz7X1d6N9wy+7vAS1q/HWiVO2FlPv0kFFopz
      7uw6GBstli7RShaO3wBFIM6/8rMKy1RqXD/TKoDRVDfy7m9hBNdU5HDjlLBb02Mg
      pdV3PzwSt11gMxmEM+hIVfokQ7+bVjDh0iL63UiMHeOaRCZXX3xNhXd7MlUeksJl
      iz84O7j5KEGR3XfFmRkrqQ4lN0F1hkXshyHCW2ah8DShH01KGtEgVPn3b2cb/j8u
      LVImRK8uXtVmmYKuPniRfwUC47Yvp5rPfG+WukUqzoj30Nm1GQFX5rA/E3ECAwEA
      AQKCAgEAnGCEbvv4zi5K3a3ZYPzmzuQTwcrikE5PKtBwlCoW2s8vgsdUD31qqK0R
      NFUunTM8O6DQ6ppvHT4aXzZJPtBLpEEF9QCo3nodol58yawdbrC9SMdfukKkj8z0
      yfwdiE7tW53+wEaUQdRZTKEBIy89Cg+pLJJ+dZVYVk8jFc/OO8aPjZHkcy5n2orO
      N2pm90QbE9U79r4CvdjsfOjJ0vXK8c55QBcO2kSNy4RogsSrjl+OE2JOANzDvfJ/
      JEzj3OdQJM+ijH2r+UpBbYZYXNhGLz6NqWkFMQyh7fcYPzh95XBai/NjEFdvTMhY
      4cX8KvCcF/vSQlJhAaMEEbGh+bThuj+Do6XQvTvxIjH6UXDWfk+eqPkfxf2OTmse
      GdM/t7hD/soX2MS02437v6F3KDE5JXe2g/PgHW+iGJpqWYV/sCV2IiO54o+9G66x
      DIsfjPmgpTjBmtI9l9ZDigjnagttp0PihGNAQ7cAI5F+mngP5iUcdGtYAWvoArKJ
      +p81VymTPUpdbw/iw8DKQVby1Zd/d7ieabQmx/JtZxX+IiP/lvmhsdic2Lan4Yrx
      kQxu8gNI3cwgs8uA/Y82c5o9PhdwaZTDcUL4Bxc9NSE/S18ixdsTfxamG7vul+qF
      dRrXOsCA6Fa5SChBHT38qUHvZKabqVkeNqZnbjZHLn7fxcxS8kECggEBAP6WHGmD
      sXO5jNPbioAWUAgWWrn1KnI3T7fh5mD3k2SZ/xZL2xbIgq7eqCZIWOfK3gQ5abv5
      GajFtxaEyQ271BEAporiif+LlNqbIWPt8flKb/VfkJFZvuJu1uB+fzLIjvdsG4IR
      dwoI1Rw3Gn/LtPKkDZdtR3RIy7FZU+yjlsMEVfVme+1dgyZHYy/oB1eDYgSdPVRx
      ng0yPMPgjebMD8SrvLP5nESKYOW+Ck3eW6btuxikmpMWTdK8O5K5mC4/XCppQ2qG
      HGenuclqJLCKdVdZC9AcYJjNdi2DZSw9fXTpQb5a+pzNetlsT+ZGauCmjV3Esw+z
      oSncGzeB6wrxWd8CggEBAMCNVMO/nr2axhxsBbjk9zUTcZKNgGPqehmqQetruHlC
      PvDccajXG795d0zz2iPVR8pR9VmU8ug+ImyG7BdWvh3jzGbnxNmM3Ed5wlaAWXKw
      ReZbtkIHBlYadgnq2r3LOd/Uda3SlflW1bioLaGackayrQncoo0Q1w9LMhwXp0mE
      Cx060ERA4VZyyBBDIGKEV7c82jHdIVjygJvuRHhDGH6TOxsh2BRQhdxmYHfLsty6
      7tCzwG+hz2keJc7mSO489xkbfMXtp/r3WNk8SgJWEd+T+/OsxBDtQrcZkOMJUm5f
      sWId4RSDwJKOWQNSeDxbx6EHl1ttkW3teqjvciLZ3K8CggEAaRI7F7Eqg8CIxsdN
      GiAbV7siJq1wn0MEu7eYBV0oj9Se2uzjtzt59AIhE+u4BbJMfyHS6amdVXKEZd7X
      u7tRgtLp6Vgl7DoHbVGpLjz+KQz3uCWA3PxVM87bEDwk8yijGKqdj8j1gEa07bgw
      T54bSCk9EsofO3bv2norkPbTOhmIAIgTjZuSjTHZVeRFY3Dt+0mKDlf2Cyw4t/7t
      kduWhmz6rKzQOdmCtE8CobCr0vE6zqjgwuPpqpfVXnEKxcuQllBraoN/JairnN0Z
      12LNmwc9QN71XxstMwuPrfqS1LWQVKfn1t9XXHS/ZSKa6azTm2ebH1fbpBMbiIUu
      JI4HsQKCAQEAr6G6SXqFTqjYP6CAb6/ZlP4RP/31uC1uBe74hcYR0/kK9CP/QGRF
      GRewK+7ZcIngG7k6M+Xa0t+qApfmzTr/2r+n9808DrufSUrUapZUAHqsp3vL+Nnz
      e6JTPKSNtUSjm3htholo5q+/7djpFliMF9RuZWpskoNjxr1uDZW9rx7UDGtTAI61
      e2bi+YJhDbttTuQgmg77lehMSu7AYXnB4+JjrVHniFASaYCwSVTx5shTgOYUhz5u
      s5EeJ2SB7VyKfspFuzwVVqM61ZtaXlsnnmmbDR7vEAl6Kw0UzSH5oFeEstxSK6Yp
      hwR0SMV2ioekxUrpUinU1xIgKeuOjh9uXQKCAQBuwor14Q9l5MXbXDoiWnmI5dlb
      pd+g+JjW6ZcPI8D4qgl42tdjyk6PKemMdOyV8pF346O//FGPvFs1qPGq/YKdnHnw
      3YCOUo7wVy4VTiK3kYkBKcVWK8A4XpiHVM7g0pSNsm4he9z3NgiAnc1aGLzv6bOr
      Zt0JDeheorZcG/ApJzToQRzXhQGbWfSL5uF/xJNTu6mospHIiORNk8hC2FuGygBQ
      +5p0nMLqzfcKJqwULujYuiYMlIZ0vkwv4gCkSTdsp9HFc333GIsrUQHIVM2DdOQr
      T93xuMGff3FrWzmUHPgQABTybKfmcwwVuXUuT10pJ0GbVMh7tX4WoOT3CTX9
      -----END RSA PRIVATE KEY-----
    termination: edge
  to:
    kind: ""
    name: image-registry
    weight: null
status: {}
