apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: registry
spec:
  port:
    targetPort: 5000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: image-registry
    weight: 100
  wildcardPolicy: None
