apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.class: "haproxy"
  name: k3s-registry
spec:
  ingressClassName: haproxy
  rules:
  - host:  ${REGISTRY_FQDN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: image-registry
            port:
              number: 5000
