apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  labels:
    {{- include "image-registry.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
